/**
 * FUTURE BACKEND CONTRACT
 * ------------------------------------------------------------------
 * The Python backend is NOT implemented yet. Every service in this
 * folder currently returns MOCK DATA. When the REST API goes live,
 * replace only the bodies of the service functions — the endpoint
 * paths and payload shapes are declared here so nothing else in the
 * UI has to change.
 */

export const API_BASE = "/api";

export const ENDPOINTS = {
  login: "POST /api/auth/login",
  register: "POST /api/auth/register",
  analyze: "POST /api/analyze",
  compare: "POST /api/analyze/compare",
  models: "GET /api/models",
  model: "GET /api/models/:id",
  datasets: "GET /api/datasets",
  uploadDataset: "POST /api/datasets/upload",
  preprocessDataset: "POST /api/datasets/:id/preprocess",
  startTraining: "POST /api/training/start",
  trainingStatus: "GET /api/training/:id",
  comparison: "GET /api/comparison",
  analytics: "GET /api/analytics",
  predictions: "GET /api/predictions",
  prediction: "GET /api/predictions/:id",
  explanation: "GET /api/predictions/:id/explanation",
} as const;

/**
 * Marks a value as produced by the local mock layer rather than a trained
 * model. Screens surface this so no result is ever mistaken for real
 * model output.
 */
export const MOCK_NOTICE =
  "Simulated result — generated by the local mock service, not a trained model.";

/** Uniform artificial latency so loading states are exercised realistically. */
export function delay<T>(value: T, ms = 420): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}
